# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18k4j6i8jjsFIgbFkegxLh89ndp0v8lPn
"""

from math import sin

f = lambda x: sin(x) + 20
a, b = 3, 6
epsilon = 0.0001
sigma = epsilon / 4

while b - a > epsilon:
  c = (a + b) / 2
  x1 = c - sigma
  x2 = c + sigma

  if f(x1) < f(x2):
    b = x2
  else:
    a = x1

print((a+b)/2)

